[package]
name = "propose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metric = { path = "../metric" }
pest = "2.0"
pest_derive = "2.0"
